
name: ann2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - matplotlib==3.5.1
  - pandas==1.3.5
  - numpy==1.21.5
  - holoviews==1.14.8
  - hvplot==0.7.3
  - panel==0.13.0
  - bokeh==2.4.2  # Critical: This version supports plot_height/plot_width
  - pillow==9.0.1
  - pyyaml==6.0
  - param==1.12.0
  - colorcet==3.0.0
  - dask
  - diskcache
  - jupyter
  - ipykernel
  # data processing
  - aiohttp
  - requests==2.28.0
  - openpyxl==3.0.5  # For Excel file handling if needed
  - pip:
    - scikit-learn==1.0.2
    - tensorflow==2.9.1
    - keras==2.9.0  # Explicitly included since it's used with tensorflow